### ISSUE TITLE
 No module named 'gundb.test'

### ISSUE THREAD

**Issue by bitnom** [xmonader/pygundb#23]
Trying to run the reference implement:

```
[2019-09-08 13:46:14 -0400] [5029] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/tensortom/.local/share/virtualenvs/project-OP1ochSq/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/tensortom/.local/share/virtualenvs/project-OP1ochSq/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/home/tensortom/.local/share/virtualenvs/project-OP1ochSq/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/tensortom/.local/share/virtualenvs/project-OP1ochSq/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/tensortom/.local/share/virtualenvs/project-OP1ochSq/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/tensortom/.local/share/virtualenvs/project-OP1ochSq/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/tensortom/.local/share/virtualenvs/project-OP1ochSq/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/tensortom/.local/share/virtualenvs/project-OP1ochSq/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/tensortom/Projects/project/pygundb/app.py", line 1, in <module>
    from gundb.test import app
ModuleNotFoundError: No module named 'gundb.test'
[2019-09-08 13:46:14 -0400] [5029] [INFO] Worker exiting (pid: 5029)
[2019-09-08 13:46:14 -0400] [5026] [INFO] Shutting down: Master
[2019-09-08 13:46:14 -0400] [5026] [INFO] Reason: Worker failed to boot.
```

**Comment by xmonader** [comment]
I'll fix that tmw, maybe master branch can work for you for testing it out?

**Comment by xmonader** [comment]
I pushed a quick fix

```
GUNDB=mem
make run
```

you can use redis instead of mem with combination with redis-desktop-manager for better visuals
