### ISSUE TITLE
RuntimeError dict changed 

### ISSUE THREAD

**Issue by xmonader** [xmonader/pygundb#25]
```
Traceback (most recent call last):
  File "/home/xmonader/.local/share/virtualenvs/pygundb-raBiLwH6/lib/python3.6/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/home/xmonader/.local/share/virtualenvs/pygundb-raBiLwH6/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "/home/xmonader/.local/share/virtualenvs/pygundb-raBiLwH6/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "/home/xmonader/.local/share/virtualenvs/pygundb-raBiLwH6/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/xmonader/.local/share/virtualenvs/pygundb-raBiLwH6/lib/python3.6/site-packages/flask_sockets.py", line 45, in __call__
    handler(environment, **values)
  File "/home/xmonader/wspace/pygundb/gundb/server.py", line 30, in gun
    server.process_message(msgstr)
  File "/home/xmonader/wspace/pygundb/gundb/gunrequesthandler.py", line 104, in process_message
    self.push_diffs(overalldiff)
  File "/home/xmonader/wspace/pygundb/gundb/gunrequesthandler.py", line 141, in push_diffs
    self.backend.put(soul, k, v, state, self.graph)
  File "/home/xmonader/wspace/pygundb/gundb/backends/backend.py", line 81, in put
    root = search(soul, graph)
  File "/home/xmonader/wspace/pygundb/gundb/backends/resolvers.py", line 120, in search
    for key, val in graph.items():
RuntimeError: dictionary changed size during iteration
2019-09-08T18:30:13Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '34468', 'HTTP_HOST': '127.0.0.1:8000', (hidden keys: 32)} failed with RuntimeError


```

**Comment by xmonader** [comment]
doesn't seem to happen anymore
