### ISSUE TITLE
add_peer not found on the handler in gevent

### ISSUE THREAD

**Issue by xmonader** [xmonader/pygundb#26]
```
Got client connection
Traceback (most recent call last):
  File "/home/xmonader/.local/share/virtualenvs/pygundb-raBiLwH6/lib/python3.6/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/home/xmonader/.local/share/virtualenvs/pygundb-raBiLwH6/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "/home/xmonader/.local/share/virtualenvs/pygundb-raBiLwH6/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "/home/xmonader/wspace/pygundb/gundb/geventserver.py", line 79, in __call__
  File "/home/xmonader/.local/share/virtualenvs/pygundb-raBiLwH6/lib/python3.6/site-packages/geventwebsocket/resource.py", line 22, in handle
    self.protocol.on_open()
  File "/home/xmonader/.local/share/virtualenvs/pygundb-raBiLwH6/lib/python3.6/site-packages/geventwebsocket/protocols/base.py", line 8, in on_open
    self.app.on_open()
  File "/home/xmonader/wspace/pygundb/gundb/geventserver.py", line 25, in on_open
    self.handler.add_peer(self.ws)
AttributeError: 'WebSocket' object has no attribute 'add_peer'
2019-09-08T18:40:31Z {'REMOTE_ADDR': '::ffff:127.0.0.1', 'REMOTE_PORT': '40058', 'HTTP_HOST': '127.0.0.1:8000', (hidden keys: 30)} failed with AttributeError

```

**Comment by xmonader** [comment]
all gevent server immediate problems fixed
